# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackDavis2020-Pets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackDavis2020-Pets
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
